// @ts-check
const {themes} = require('prism-react-renderer');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Anthill',
  tagline: 'Your owned GPT that runs on open-weight models, in your environment.',
  url: 'https://docs.anthill.run',
  baseUrl: '/',
  organizationName: 'OneHillAI',
  projectName: 'Anthill',
  onBrokenLinks: 'warn',
  markdown: {
    // Some source docs mix raw HTML into markdown (fine for GitHub's renderer). MDX's JSX parser
    // is much stricter about that (unclosed/self-closing tags), so use plain Markdown site-wide.
    format: 'md',
    hooks: {onBrokenMarkdownLinks: 'warn'},
  },
  i18n: {defaultLocale: 'en', locales: ['en']},
  presets: [
    ['classic', {
      docs: {
        routeBasePath: '/',
        sidebarPath: require.resolve('./sidebars.js'),
        // docs-site/docs/ is generated by scripts/collect-docs.js (an explicit publish
        // whitelist), not authored directly - see that script before adding a page here.
        editUrl: ({docPath}) => {
          const source = docPath === 'README.md' ? 'docs/DOCS_OVERVIEW.md' : `docs/${docPath}`;
          return `https://github.com/OneHillAI/Anthill/edit/main/${source}`;
        },
      },
      blog: false,
      theme: {customCss: require.resolve('./src/css/custom.css')},
    }],
  ],
  themeConfig: {
    navbar: {
      title: 'Anthill',
      logo: {alt: 'Anthill', src: 'img/logo.svg'},
      items: [
        {href: 'https://anthill.run', label: 'anthill.run', position: 'right'},
        {href: 'https://github.com/OneHillAI/anthill', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'light',
      links: [
        {
          title: 'Anthill',
          items: [
            {label: 'anthill.run', href: 'https://anthill.run'},
            {label: 'Features', href: 'https://anthill.run/features'},
            {label: 'Download', href: 'https://anthill.run/download'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'GitHub', href: 'https://github.com/OneHillAI/anthill'},
            {label: 'Licence', href: 'https://anthill.run/license'},
            {label: 'OneHill', href: 'https://onehill.org'},
          ],
        },
      ],
      copyright: 'Anthill is AGPL-3.0. © 2026 OneHill Foundation.',
    },
    prism: {theme: themes.github, darkTheme: themes.dracula},
  },
};
module.exports = config;
