from __future__ import annotations

import logging
import os
import tempfile
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path

from ..common.text import first_h1, slugify, strip_frontmatter

log = logging.getLogger(__name__)

SCHEMA_SEED = """# Wiki schema

This file tells the model how to maintain this wiki. It is the only layer a human
edits directly to change behavior.

## Layers
- `raw/`   - immutable source documents. Never edited after ingest.
- `inbox/` - sources dropped here, awaiting ingest.
- `wiki/`  - model-owned Markdown pages. The model creates and revises these.
- `index.md` - generated catalog of every page. Do not hand-edit.
- `log.md`   - append-only timeline of what happened.

## Page conventions
- One topic per page. Filename is the slug; the page opens with an `# H1` title.
- Second line is a one-sentence summary. The index is built from these two lines.
- Link related pages with `[[other-slug]]`. Prefer many small linked pages over
  one large page.
- State claims concretely and attribute them to their source where it matters.

## Workflows
- **Ingest**: read a source, write/update the pages it touches, link them, and add a
  `log.md` entry. A single source usually touches several pages.
- **Answer**: answer from the wiki first; cite the pages used. A good answer can be
  filed back as its own page so the knowledge compounds.
- **Lint**: flag contradictions, stale claims, orphan pages, and broken links.
"""

PRINCIPLES_SEED = """<!--
PRINCIPLES.md - standing principles for this scope.

Anything you write OUTSIDE these comment markers is applied to EVERY answer and
agent action in this scope (organization, team, or you). Keep it short - a few lines.
Examples:
  - Tone: concise and direct; no preamble.
  - Never share customer data outside the organization.
  - Prefer self-hosted options when recommending tools.

Delete this comment block and write your principles below.
-->
"""

_INDEX_HEADER = (
    "# Index\n\nEvery wiki page, newest first. Generated by anthill - do not hand-edit.\n"
)


@dataclass
class Workspace:
    root: Path
    scope: str = ""  # personal | team | org - stamped into each page as OKGF x-anthill-scope

    @property
    def raw(self) -> Path:
        return self.root / "raw"

    @property
    def inbox(self) -> Path:
        return self.root / "inbox"

    @property
    def wiki(self) -> Path:
        return self.root / "wiki"

    @property
    def index_md(self) -> Path:
        return self.root / "index.md"

    @property
    def log_md(self) -> Path:
        return self.root / "log.md"

    @property
    def schema_md(self) -> Path:
        return self.root / "SCHEMA.md"

    @property
    def principles_md(self) -> Path:
        return self.root / "PRINCIPLES.md"

    @property
    def skills(self) -> Path:
        return self.root / "skills"

    def exists(self) -> bool:
        return self.schema_md.exists()

    def init(self) -> None:
        for d in (self.raw, self.inbox, self.wiki, self.skills):
            d.mkdir(parents=True, exist_ok=True)
        if not self.schema_md.exists():
            self.schema_md.write_text(SCHEMA_SEED)
        if not self.principles_md.exists():
            self.principles_md.write_text(PRINCIPLES_SEED)
        if not self.log_md.exists():
            self.log_md.write_text("# Log\n\n")
        self.rebuild_index()

    def pages(self) -> list[Path]:
        return sorted(self.wiki.glob("*.md"))

    @property
    def meili_index(self) -> str:
        """A Meilisearch index unique to this workspace (keyed on its root). Without this, every scope
        upserted into one flat index keyed by slug alone, so a personal 'roadmap' and the org 'roadmap'
        collided (last write wins) and polluted each other's ranking. One index per workspace keeps each
        scope's search isolated."""
        import hashlib

        return "anthill-wiki-" + hashlib.sha256(str(self.root).encode()).hexdigest()[:16]

    def write_page(
        self,
        title_or_slug: str,
        markdown: str,
        *,
        review: str = "",
        tier: str = "",
        sources: list[str] | None = None,
    ) -> Path:
        """Write a page in the native OKGF format: OKF frontmatter (type/title/timestamp + this
        workspace's ``x-anthill-scope``, plus any review/tier/sources) over the markdown body. The
        body keeps Anthill's ``[[slug]]`` authoring shorthand (only the export view in ``okf`` rewrites
        those to OKF links). Any frontmatter already on the input is stripped first, so re-saving a page
        never double-wraps it."""
        from . import okf

        body = strip_frontmatter(markdown).strip()
        page = okf.OkfPage(
            type="Concept",
            title=first_h1(body) or title_or_slug,
            description=_first_para(body),
            timestamp=datetime.now(timezone.utc).isoformat(),
            body=body,
            scope=self.scope,
            review=review,
            tier=tier,
            sources=sources or [],
        )
        path = self.wiki / f"{slugify(title_or_slug)}.md"
        path.write_text(okf.to_okf(page))
        # Embed the saved page in the background so the first question that needs it finds it ready.
        from .page_index import warm_page_soon

        warm_page_soon(self.root, path)
        return path

    def migrate_to_okgf(self) -> int:
        """Rewrite legacy (frontmatter-less) pages in this workspace into native OKGF, stamping this
        scope. Idempotent: a page that already has frontmatter is left untouched. Returns the count
        migrated. Safe to run repeatedly; pages also migrate lazily on their next ``write_page``."""
        migrated = 0
        for p in self.pages():
            text = p.read_text()
            if strip_frontmatter(text) != text:
                continue  # already has frontmatter (strip changed it) -> leave it
            self.write_page(p.stem, text)
            migrated += 1
        return migrated

    def append_log(self, kind: str, title: str) -> None:
        with self.log_md.open("a") as fh:
            fh.write(f"## [{date.today().isoformat()}] {kind} | {title}\n")

    def rebuild_index(self) -> None:
        rows = []
        for p in self.pages():
            title, summary = _title_summary(p)
            rows.append((p.stat().st_mtime, p.stem, title, summary))
        rows.sort(reverse=True)  # newest first
        lines = [_INDEX_HEADER]
        for _mtime, stem, title, summary in rows:
            lines.append(
                f"- [{title}]({stem}.md) - {summary}" if summary else f"- [{title}]({stem}.md)"
            )
        self.index_md.write_text("\n".join(lines) + "\n")
        # Mirror into Meilisearch when configured (opt-in, self-hosted). Best-effort.
        try:
            from ..search import meili

            if meili.enabled():
                meili.index_pages(self.pages(), index=self.meili_index)
        except Exception:
            pass


_OWNER_MARKER = ".owner-org"


def _legacy_org_wiki_root() -> Path:
    return Path(os.environ.get("ANTHILL_ORG_WIKI", "data/org-wiki"))


def org_wikis_base() -> Path:
    """Folder that holds the org wikis of every organisation other than the one that owns the legacy
    ``ANTHILL_ORG_WIKI`` folder (``ANTHILL_ORG_WIKIS`` overrides; default: a sibling named ``org-wikis``).
    It is a sibling, not a child, so exporting or backing up one org's wiki never includes another's."""
    env = os.environ.get("ANTHILL_ORG_WIKIS")
    return Path(env) if env else _legacy_org_wiki_root().parent / "org-wikis"


def legacy_org_wiki_owner() -> int | None:
    """The organisation that owns the legacy ``ANTHILL_ORG_WIKI`` folder, or None when not recorded yet."""
    return _read_owner(_legacy_org_wiki_root() / _OWNER_MARKER)


def _read_owner(marker: Path) -> int | None:
    try:
        return int(marker.read_text().strip())
    except (OSError, ValueError):
        return None


def claim_legacy_org_wiki(org_id: int) -> bool:
    """Record ``org_id`` as the owner of the legacy org wiki folder, once. Called at start-up with the
    first admin's organisation (so an existing install keeps its pages) and after the first organisation of
    a fresh install is created. Never changes an owner that is already recorded.

    The marker is created exclusively: the owner is written to a temporary file with a name no other process
    shares and hard-linked into place, so two claims cannot both succeed and the first stays. A filesystem
    without hard links falls back to creating the marker with ``O_EXCL``. A failure is logged, not raised (the
    install keeps working on the default owner). Returns True when this call recorded the owner."""
    if legacy_org_wiki_owner() is not None:
        return False
    root = _legacy_org_wiki_root()
    marker = root / _OWNER_MARKER
    text = f"{int(org_id)}\n"
    tmp = None
    try:
        root.mkdir(parents=True, exist_ok=True)
        handle, tmp_name = tempfile.mkstemp(prefix=f"{_OWNER_MARKER}.", suffix=".tmp", dir=root)
        tmp = Path(tmp_name)
        with os.fdopen(handle, "w") as fh:
            fh.write(text)
        for _attempt in (1, 2):
            try:
                os.link(tmp, marker)
            except FileExistsError:
                if _read_owner(marker) is not None:
                    return False
                marker.unlink(missing_ok=True)  # empty or unreadable (a crash): replace it
                continue
            except OSError:
                return _claim_with_excl(marker, text)  # no hard links here
            return True
        return False
    except OSError as exc:
        log.warning("could not record the owner of the org wiki folder %s: %s", root, exc)
        return False
    finally:
        if tmp is not None:
            tmp.unlink(missing_ok=True)


def _claim_with_excl(marker: Path, text: str) -> bool:
    """Create the marker with O_EXCL (for a filesystem that cannot hard-link). An empty or unreadable marker
    left by a crash is replaced once."""
    for _attempt in (1, 2):
        try:
            fd = os.open(marker, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644)
        except FileExistsError:
            if _read_owner(marker) is not None:
                return False
            marker.unlink(missing_ok=True)  # a half-made marker: clear it and try once more
            continue
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        return True
    return False


def org_wiki_root(org_id=None) -> Path:
    """Folder of an organisation's wiki. The owner of the legacy folder (the first admin's organisation, so
    an existing install keeps its pages in place) uses it; every other organisation has
    ``org-wikis/org-<id>``. Before an owner is recorded, organisation 1 is the owner. With no ``org_id`` it is
    the legacy folder: only for system code that has no signed-in organisation (see
    ``legacy_org_wiki_workspace``); ``workspace_for`` itself requires an ``org_id`` for the org scope."""
    legacy = _legacy_org_wiki_root()
    if org_id is None:
        return legacy
    owner = legacy_org_wiki_owner()
    if owner is None:
        owner = 1
    if int(org_id) == owner:
        return legacy
    return org_wikis_base() / f"org-{int(org_id)}"


def legacy_org_wiki_workspace() -> Workspace:
    """The legacy ``ANTHILL_ORG_WIKI`` folder as a workspace, whichever organisation owns it. Only for code
    that moves or inspects that folder itself (the shared-wiki notice at start-up, tests); anything that acts
    for an organisation uses ``workspace_for("org", org_id=...)``."""
    return Workspace(_legacy_org_wiki_root(), scope="org")


def workspace_for(scope: str = "personal", *, user_id=None, team_id=None, org_id=None) -> Workspace:
    """Resolve the Workspace for a knowledge scope on the ladder.

    - ``org``  -> that organisation's wiki (see ``org_wiki_root``). ``org_id`` is required: leaving it out
      would silently pick another organisation's folder, so it raises ``ValueError``.
    - ``team`` -> ``ANTHILL_WIKI_ROOT/team-<team_id>``.
    - ``personal`` -> ``ANTHILL_WIKI_ROOT/user-<user_id>`` when a user is given;
      otherwise the single-node ``ANTHILL_WORKSPACE`` (the alpha default, kept so
      existing installs and the CLI keep using their one personal wiki).

    This is the one place wiki paths are decided. Callers pass scope + ids; nobody
    else hardcodes a path.
    """
    if scope == "org":
        if org_id is None:
            raise ValueError("the org wiki belongs to an organisation: pass org_id")
        return Workspace(org_wiki_root(org_id), scope="org")
    root = Path(os.environ.get("ANTHILL_WIKI_ROOT", "data/wikis"))
    if scope == "team":
        return Workspace(root / f"team-{team_id}", scope="team")
    if user_id is None:  # alpha single-node personal default
        return Workspace(Path(os.environ.get("ANTHILL_WORKSPACE", "workspace")), scope="personal")
    return Workspace(root / f"user-{user_id}", scope="personal")


def migrate_legacy_personal_wiki(user_id) -> int:
    """One-time, idempotent: fold the legacy single-node personal wiki into a user's per-user wiki.

    The personal wiki used to live in one ``ANTHILL_WORKSPACE`` dir; it is now per-user
    (``ANTHILL_WIKI_ROOT/user-<id>``). Now that plain chat resolves personal per-user, an existing
    install's pages would otherwise vanish from chat. So copy the legacy pages into ``user-<user_id>``
    (the creator/admin), once. Copy - not move - so the legacy dir still serves the system/scheduler
    path; a ``.personal-migrated`` marker in the legacy dir stops it re-running. Never overwrites an
    existing per-user page. Returns the number of pages copied (0 when there is nothing to do)."""
    import shutil

    legacy_root = Path(os.environ.get("ANTHILL_WORKSPACE", "workspace"))
    marker = legacy_root / ".personal-migrated"
    if not legacy_root.exists() or marker.exists():
        return 0
    target = workspace_for("personal", user_id=user_id)
    if target.root.resolve() == legacy_root.resolve():  # paths coincide - nothing to migrate
        marker.write_text("noop: legacy path == per-user path\n")
        return 0
    legacy_ws = Workspace(legacy_root, scope="personal")
    pages = legacy_ws.pages()
    if not pages:
        marker.write_text("noop: no legacy pages\n")
        return 0
    if not target.exists():
        target.init()
    copied = 0
    for p in pages:
        dest = target.wiki / p.name
        if not dest.exists():  # never clobber a page the user already has per-user
            shutil.copy2(p, dest)
            copied += 1
    if copied:
        target.rebuild_index()
    marker.write_text(f"copied {copied} page(s) into {target.root}\n")
    return copied


def _first_para(markdown: str) -> str:
    """First non-empty, non-heading line of the body (frontmatter stripped) - a one-line summary."""
    for line in strip_frontmatter(markdown).splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            return s
    return ""


def _title_summary(path: Path) -> tuple[str, str]:
    text = path.read_text()
    return (first_h1(text) or path.stem), _first_para(text)
