#!/usr/bin/env python3
"""Rebuild assets/anthill-logo.png (the README banner) in the app's green/white identity.

assets/anthill-logo.png is a standalone, hand-set asset - a wordmark + subtitle next to the
mound glyph - not one of the icon tiles scripts/gen_icons.py produces, so it doesn't get
regenerated by that script and has to be migrated on its own whenever the brand palette moves.

This reads the asset as it exists at the given source ref (the original amber-on-cream artwork,
before any prior palette migration), and:

  1. Recolors the whole background from the old cream to the app's white (the "Anthill" wordmark's
     dark ink is decomposed out and kept unchanged - only what it's anti-aliased against moves).
  2. Recolors the mound (dome/ridges/entrance/ground) from the old amber family to the app's
     --accent pine green family (scripts/gen_icons.py's DOME/RIDGE/GROUND/SOIL), by decomposing
     each mound pixel as an alpha blend between old reference colors and reconstructing it with
     the same alpha against the new ones - reproducing the original anti-aliasing exactly instead
     of re-drawing the mound.
  3. Erases the subtitle and re-renders "by OneHill" in the new accent green, in the same font,
     size, and baseline the original subtitle used (the org renamed from Colonies AI to OneHill;
     see scripts/fix_logo_banner_subtitle.py's history for that fix on its own).

Run once after a palette or brand change:
  git show <ref>:assets/anthill-logo.png > /tmp/original-banner.png
  python scripts/recolor_logo_banner.py /tmp/original-banner.png
"""

from __future__ import annotations

import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = "assets/anthill-logo.png"

WHITE_NEW = (0xFF, 0xFF, 0xFF)  # --surface
INK_OLD = (26, 17, 10)  # wordmark ink; unchanged, decomposed out of the bg recolor

CREAM_OLD = (250, 245, 237)

# (old color as drawn in the original amber-on-cream asset, new vivid-green color - see
# scripts/gen_icons.py's DOME/RIDGE/GROUND/SOIL comment for why DOME isn't a plain --accent tint)
MOUND_REFS = [
    ("cream", CREAM_OLD, WHITE_NEW),
    ("dome", (212, 137, 26), (0x3D, 0x8B, 0x63)),  # DOME
    ("ridge", (188, 115, 21), (0x1F, 0x5C, 0x40)),  # RIDGE
    ("ground", (193, 144, 82), (0x15, 0x46, 0x30)),  # GROUND
    ("soil", (26, 17, 10), (0x08, 0x1C, 0x13)),  # SOIL (entrance)
]
MOUND_BBOX = (60, 170, 300, 270)  # mound region with margin, clear of the wordmark (x>=355)

SUBTITLE_COLOR = (0x1F, 0x5C, 0x40)  # RIDGE - echoes the mound's mid-tone
FONT_PATH = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
SUBTITLE_SIZE = 42
SUBTITLE_ORIGIN = (358, 221)  # calibrated so the rendered bbox lands where the old subtitle sat
SUBTITLE_ERASE_BOX = (350, 215, 670, 280)  # covers the old subtitle's glyph bounds with margin
SUBTITLE_TEXT = "by OneHill"


def _best_pair_alpha(p, refs):
    """Best-fit (alpha, new_a, new_b) so that p ~= alpha*old_a + (1-alpha)*old_b."""
    best = None
    for _, a_old, a_new in refs:
        for _, b_old, b_new in refs:
            if a_old == b_old:
                continue
            num = sum((p[c] - b_old[c]) * (a_old[c] - b_old[c]) for c in range(3))
            den = sum((a_old[c] - b_old[c]) ** 2 for c in range(3))
            if den == 0:
                continue
            alpha = max(0.0, min(1.0, num / den))
            res = sum(
                (p[c] - (alpha * a_old[c] + (1 - alpha) * b_old[c])) ** 2 for c in range(3)
            )
            if best is None or res < best[0]:
                best = (res, alpha, a_new, b_new)
    return best


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else ROOT
    im = Image.open(src).convert("RGB")
    w, h = im.size
    orig = im.load()
    out = Image.new("RGB", (w, h))
    out_px = out.load()

    bg_refs = [("cream", CREAM_OLD, WHITE_NEW), ("ink", INK_OLD, INK_OLD)]
    x0, y0, x1, y1 = MOUND_BBOX
    for y in range(h):
        for x in range(w):
            p = orig[x, y]
            if x0 <= x < x1 and y0 <= y < y1:
                if p == CREAM_OLD:
                    out_px[x, y] = WHITE_NEW
                    continue
                _, alpha, a_new, b_new = _best_pair_alpha(p, MOUND_REFS)
            else:
                if p == CREAM_OLD:
                    out_px[x, y] = WHITE_NEW
                    continue
                if p == INK_OLD:
                    out_px[x, y] = INK_OLD
                    continue
                _, alpha, a_new, b_new = _best_pair_alpha(p, bg_refs)
            out_px[x, y] = tuple(
                round(alpha * a_new[c] + (1 - alpha) * b_new[c]) for c in range(3)
            )

    d = ImageDraw.Draw(out)
    d.rectangle(SUBTITLE_ERASE_BOX, fill=WHITE_NEW)
    font = ImageFont.truetype(FONT_PATH, SUBTITLE_SIZE)
    d.text(SUBTITLE_ORIGIN, SUBTITLE_TEXT, font=font, fill=SUBTITLE_COLOR)

    out.save(ROOT)
    print("wrote", ROOT)


if __name__ == "__main__":
    main()
