#!/usr/bin/env bash
# ASDD - post the advisory review comment. Runs ONLY in the write-scoped publish workflow.
#
# Consumes review.json as DATA and posts an advisory comment via the GitHub API (a fixed action, not a
# shell-exec of model output). It posts; it never merges. Disclosure is baked into the comment header.
#
# Usage: post-review.sh <review.json>
# Env: GH_TOKEN, REPO (owner/name).
set -euo pipefail

REVIEW="${1:?usage: post-review.sh <review.json>}"
: "${GH_TOKEN:?GH_TOKEN required}"
: "${REPO:?REPO (owner/name) required}"

PR="$(jq -r '.pr_number' "$REVIEW")"
[[ "$PR" =~ ^[0-9]+$ ]] || { echo "post-review: invalid pr_number" >&2; exit 1; }

MODE="$(jq -r '.mode // "live"' "$REVIEW")"
REC="$(jq -r '.recommendation // "comment"' "$REVIEW")"
SUMMARY="$(jq -r '.summary // ""' "$REVIEW")"

LENSES="$(jq -r '
  (.lenses // []) | map(
    "### " + (.lens|ascii_upcase) + " - " + (.verdict // "n/a") + "\n" +
    ((.findings // []) | if length==0 then "_No findings._\n"
      else map("- " + (.severity // "note") + ": " + (.message // .)) | join("\n") + "\n" end)
  ) | join("\n")
' "$REVIEW")"

NOTE=""
case "$MODE" in
  live) ;;
  dry-run) NOTE=$'\n> **No AI review ran (dry-run).** No agent runtime is wired, so this is a placeholder. The lenses become live once a runtime is connected.\n' ;;
  adapter-template) NOTE=$'\n> **No AI review ran.** The runtime adapter is selected but no model endpoint is wired, so this is a placeholder.\n' ;;
  degraded) NOTE=$'\n> **No usable AI review.** The model was reached but its answer could not be used, so a human must review this PR.\n' ;;
  *) NOTE=$'\n> **No AI review ran** (mode: '"${MODE}"$'). A human must review this PR.\n' ;;
esac

BODY="$(cat <<MD
**ASDD review - advisory** (recommendation: \`${REC}\`)

> Produced by an automated agent under human direction. Advisory only: a human approves and merges.
> Nothing here merges automatically.
${NOTE}
${SUMMARY}

${LENSES}

---
<sub>Generated by the [ASDD](https://github.com/OneHillAI/ASDD) advisory review. Mode: \`${MODE}\`.</sub>
MD
)"

echo "post-review: posting advisory comment to ${REPO}#${PR} (mode=${MODE}, rec=${REC})"
gh api "repos/${REPO}/issues/${PR}/comments" -f body="$BODY" >/dev/null
echo "post-review: done"
